# Generated by Django 4.0.3 on 2022-04-23 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 23, 17, 37, 42, 914902, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
