# Generated by Django 4.0.3 on 2022-05-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_like_added_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='question',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='point',
        ),
        migrations.DeleteModel(
            name='DisLike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
