# Generated by Django 4.0.3 on 2022-04-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_update',
            field=models.IntegerField(default=1),
        ),
    ]
